import { yupDateOptional, yupIdOptional, yupNumberOptionalMinMax, yupStringOptional, yupStringRequired } from "./yup_utils";

export const deliverydetail_schema = {
	booking_branch: yupStringOptional,
	consignment_date: yupDateOptional,
	consignment_number: yupStringOptional,
	id: yupNumberOptionalMinMax(1), // autogenerated-serial
	invoice_id: yupIdOptional,
	payment_id: yupIdOptional, // FK
	type: yupStringRequired
		.transform((v: string, o: string) => {
			if (o === "transport") return "deliverydetail";
			return v;
		})
		.oneOf(["deliverydetail"])
		.default("deliverydetail"),
	transport_id: yupNumberOptionalMinMax(1), //FK
	transport_name: yupStringOptional,
	number_of_bales: yupNumberOptionalMinMax(0),
};

export interface SaDeliverydetail {
	/** auto increment id */
	id: number;
	/** type = deliverydetail */
	type: string;
	/** booking branch */
	booking_branch: string | null;
	/** consignment date in YYYYMMDD format */
	consignment_date: string | null;
	/** consignment number */
	consignment_number: string | null;
	/** transport name */
	transport_name: string | null;
	/** number of bales */
	number_of_bales: number | null;
	/** primary key for the table which is = <ownercompany_id><serial_number.padStart(6,'0')>  example:1000001 */
	invoice_id: string | null;
	/** auto increment id */
	payment_id: number | null;
	/** auto increment id */
	transport_id: number | null;
}
