name: Deploy AWS Lambda

on:
  push:
    branches:
      - aws-lambda-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --production

      - name: Build TypeScript Code
        run: npm run build

      - name: Zip Deployment Package
        run: zip -r lambda.zip build node_modules package.json

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name pdf-service-sa \
            --zip-file fileb://lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
